### ISSUE TITLE
[김민기] Authentication-Filter

### ISSUE THREAD

**Issue by meengi07** [FC-InnerCircle/be1-oss-library#14]
## 프로젝트 이름

Authentication-Filter

## 개요

Spring Security 에서 매번 반복되는 Authentication Filter의 필터링 로직을 컴포넌트화해서 쉽게 사용할 수 있는 라이브러리입니다.

## 저장소 주소

https://github.com/meengi07/Authentication-Filter

## 체크리스트

- [x] 개인 저장소 생성
- [ ] README.md 파일 작성 (다음 항목 포함)
  - [ ] 프로젝트 개요
  - [ ] 설치 방법 / 사용 방법
  - [ ] 라이선스 표기
- [ ] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [ ] Jitpack을 이용해 GitHub에 라이브러리 릴리즈

**Comment by heli-os** [comment]
👍

**Comment by heli-os** [comment]
조금 더 구체적으로 어떤 필터링 로직을 포함하게 될지 먼저 설계해보신 후 진행하시면 좋을 것 같습니다.
