### ISSUE TITLE
[김성현] Async Alert message service

### ISSUE THREAD

**Issue by kimsunghyun1995** [FC-InnerCircle/be1-oss-library#16]
## 프로젝트 이름

-  Async Alert message service

## 개요

- Async하게 외부 메시지를 호출할 수 있는 API

## 저장소 주소

저장소 링크를 남겨주세요.

## 체크리스트

- [ ] 개인 저장소 생성
- [ ] README.md 파일 작성 (다음 항목 포함)
  - [ ] 프로젝트 개요
  - [ ] 설치 방법 / 사용 방법
  - [ ] 라이선스 표기
- [ ] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [ ] Jitpack을 이용해 GitHub에 라이브러리 릴리즈

**Comment by heli-os** [comment]
설명이 모호한데요. 조금 더 구체적으로 남겨주실 수 있으실까요?

Executor interface 구현체와는 다른걸까요?

**Comment by kimsunghyun1995** [comment]
> 설명이 모호한데요. 조금 더 구체적으로 남겨주실 수 있으실까요?
> 
> Executor interface 구현체와는 다른걸까요?

넵 해당 주제 변경하였습니다.

구현하다 보니, 너무 애매한 주제인 것 같아서,, 외부 API에 대해 유저가 설정한 Rate Limit에 맞게 호출하는 라이브러리로 변경하려고 합니다!

**Comment by heli-os** [comment]
> > 설명이 모호한데요. 조금 더 구체적으로 남겨주실 수 있으실까요?
> > Executor interface 구현체와는 다른걸까요?
> 
> 넵 해당 주제 변경하였습니다.
> 
> 구현하다 보니, 너무 애매한 주제인 것 같아서,, 외부 API에 대해 유저가 설정한 Rate Limit에 맞게 호출하는 라이브러리로 변경하려고 합니다!

해당 이슈 원래대로 돌려서 close 하고 새로운 이슈로 올려주세요.
