### ISSUE TITLE
[김민기] LogSweep

### ISSUE THREAD

**Issue by meengi07** [FC-InnerCircle/be1-oss-library#19]
## 프로젝트 이름

LogSweep

## 개요

서버 시간 기준으로 매일 00시에 실행되는 로그 파일 관리 라이브러리
애플리케이션의 .log 파일을 00시 이전일자로 file_yyyyMMdd.log 처럼 저장하고 .log 파일 내용을 초기화하는 라이브러리
logback.xml 의 내용과 properties 설정을 바탕으로 설정?

## 저장소 주소

https://github.com/meengi07/LogSweep

## 체크리스트

- [x] 개인 저장소 생성
- [ ] README.md 파일 작성 (다음 항목 포함)
  - [ ] 프로젝트 개요
  - [ ] 설치 방법 / 사용 방법
  - [ ] 라이선스 표기
- [ ] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [ ] Jitpack을 이용해 GitHub에 라이브러리 릴리즈

**Comment by heli-os** [comment]
log4j에는 RollingFileAppender을 지원하고 있습니다.

> https://logging.apache.org/log4j/2.x/manual/appenders.html#rollingfileappender

1.x 버전에는 DailyRollingFileAppender가 있었고, 2.x 버전에서는 조금 다른 방식으로 동일한 동작을 제공하는데 해당 Appender를 이용하는 것과 다른점이 있을까요?

**Comment by meengi07** [comment]
아 그러네요.. 지원한다는걸 잊고 작성했습니당.. 오늘까진 주제 좀 고민해볼게요
