### ISSUE TITLE
[최현웅] lexo-rank

### ISSUE THREAD

**Issue by choi1204** [FC-InnerCircle/be1-oss-library#8]
## 프로젝트 이름
lexo-rank

## 개요
지라의 Lexo-Rank 알고리즘을 적용하여 문자열의 사전적 순서를 기반으로 실시간으로 항목의 순서를 동적으로 재배치하고, 순위값 고갈을 감지하여 충돌 없이 안정적인 정렬을 유지하는 확장 가능한 오픈 라이브러리를 제공합니다. 
중복과 충돌을 방지하는 정교한 순위 부여 방식을 통해 일관된 순서를 유지하며, 수십만 개 이상의 항목을 처리할 수 있는 확장성을 제공합니다.
드래그 앤 드롭과 같은 사용자 인터페이스와 결합하여 직관적이고 유연한 정렬 관리를 제공하여 사용자가 항목을 쉽게 재배치할 수 있습니다.

## 저장소 주소
https://github.com/choi1204/lexo-rank

## 체크리스트

- [x] 개인 저장소 생성
- [ ] README.md 파일 작성 (다음 항목 포함)
  - [ ] 프로젝트 개요
  - [ ] 설치 방법 / 사용 방법
  - [ ] 라이선스 표기
- [ ] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [ ] Jitpack을 이용해 GitHub에 라이브러리 릴리즈

**Comment by heli-os** [comment]
안녕하세요, 현웅님. 해당 알고리즘을 드래그 앤 드롭 정렬에 어떻게 사용하시게 되시는걸까요? 해당 연관관계에 대한 추가 설명 부탁드립니다.

**Comment by choi1204** [comment]
드래그 앤 드롭 정렬은 하나의 유즈케이스고,
대규모 데이터 셋에서, 중간삽입 시에 효율적으로 동작하는 정렬 알고리즘 기능인 lexo-rank를 라이브러리 형태로 제공하는게 목적입니다.

**Comment by heli-os** [comment]
@choi1204 요거 close 처리 해주신 이유가 있으실까요?
